server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    hibernate:
      hbm2ddl:
        auto: create
      show_sql: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/gloomy;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console


security:
  allowedOrigins: http://localhost:8080,http://localhost:3000

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
